import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';
import Image from 'next/image';
import { SanityLive } from '@/sanity/lib/live';
import { draftMode } from 'next/headers';
import { DisableDraftMode } from '@/components/store/DisableDraftModeButton';
import { VisualEditing } from 'next-sanity';
import Header from '@/components/Header';
import { ClerkProvider } from '@clerk/nextjs';

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});
export const metadata: Metadata = {
  title: 'E-Commerce',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} mx-auto max-w-5xl antialiased`}>
        {(await draftMode()).isEnabled && (
          <>
            <DisableDraftMode />
            <VisualEditing />
          </>
        )}
        <ClerkProvider
          afterSignOutUrl={'/store'}
          signInForceRedirectUrl={'/store'}
          signUpForceRedirectUrl={'/store'}
          afterSignInUrl={'/store'}
          afterSignUpUrl={'/store'}
          dynamic
        >
          <main>
            <Header />
            {children}
          </main>
        </ClerkProvider>
        <SanityLive />
      </body>
    </html>
  );
}
