import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '../globals.css'
import Image from 'next/image'
import HeaderKita from '@/components/kita/HeaderKita'
import HeroKita from '@/components/kita/HeroKita'
import { SanityLive } from '@/sanity/lib/live'
import BannerKita from '@/components/kita/BannerKita'
import { draftMode } from 'next/headers'
import { DisableDraftMode } from '@/components/store/DisableDraftModeButton'
import { VisualEditing } from 'next-sanity'

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'E-Commerce',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-5xl mx-auto`}
      >
        {(await draftMode()).isEnabled && (
          <>
            <DisableDraftMode />
            <VisualEditing />
          </>
        )}
        <Image
          width="200"
          height="135"
          priority
          className="w-screen h-screen object-cover fixed top-0 left-0 z-[-1]"
          style={{ borderRadius: '8px' }}
          src="/wood_bg.webp"
          alt=""
        />
        <BannerKita />
        <HeaderKita />
        <HeroKita />

        <main className="page__wrapper bg-white py-6 px-5">{children}</main>

        <section className="w-full shadow-md border-t border-t-black border-solid overflow-hidden">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2370.26157719655!2d9.924160212738071!3d53.553097859117806!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47b1858ff5d4109f%3A0xb33c6818ae0967ae!2sMottenkiste%20e.V.!5e0!3m2!1sen!2sde!4v1730537716459!5m2!1sen!2sde"
            width="1280"
            height="450"
            style={{ border: 0 }}
            allowFullScreen
            loading="lazy"
            referrerPolicy="no-referrer-when-downgrade"
          ></iframe>
        </section>

        <footer className="bg-white py-6 px-5 border-t border-t-black border-solid">
          <p className="text-center">Footer</p>
        </footer>

        <SanityLive />
      </body>
    </html>
  )
}
