import React from 'react'

export const metadata = {
  title: 'This is the layout store',
  description: 'Generated by create next app',
}

const RootLayout = function({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}

export default RootLayout
