import React from 'react'

export const metadata = {
  title: 'This is the layout store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>): JSX.Element {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
