import type { Metadata } from 'next';
import '../globals.css';
import HeaderStore from '@/components/store/HeaderStore';
import { SanityLive } from '@/sanity/lib/live';
import { draftMode } from 'next/headers';
import { VisualEditing } from 'next-sanity';
import { DisableDraftMode } from '@/components/store/DisableDraftModeButton';

export const metadata: Metadata = {
  title: 'E-Commerce',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {(await draftMode()).isEnabled && (
        <>
          <DisableDraftMode />
          <VisualEditing />
        </>
      )}
      <main>
        <HeaderStore />
        {children}
      </main>
      <SanityLive />
    </>
  );
}
